const fs = require('fs');
const puppeteerExtra = require('puppeteer-extra');
const pluginStealth = require('puppeteer-extra-plugin-stealth');
const pluginProxy = require('puppeteer-extra-plugin-proxy');


const util = require('util');

const isTest = false;
const useProxy = false;


const proxies = ["us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7000:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7001:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7002:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7003:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7004:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7005:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7006:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7007:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7008:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7009:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7010:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7011:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7012:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7013:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7014:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7015:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7016:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7017:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7018:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7019:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7020:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7021:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7022:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7023:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7024:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7025:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7026:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7027:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7028:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7029:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7030:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7031:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7032:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7033:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7034:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7035:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7036:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+6:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+7:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+8:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+9:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+10:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+11:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7037:orolpnlm8wevu6sgpijrps+12:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7038:orolpnlm8wevu6sgpijrps+0:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7038:orolpnlm8wevu6sgpijrps+1:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7038:orolpnlm8wevu6sgpijrps+2:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7038:orolpnlm8wevu6sgpijrps+3:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7038:orolpnlm8wevu6sgpijrps+4:zfphnxrwhx",
    "us-prime.resdleafproxies.com:7038:orolpnlm8wevu6sgpijrps+5:zfphnxrwhx"
]

let proxyRegex = /([^:]*):([^:]*):([^:]*):([^:]*)/;
let proxyIndex = 0;

const chromeOptions = (prox) => ( {
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    slowMo: 10,
    defaultViewport: null,
    args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        (isTest || !useProxy) ? '' : `--proxy-server=https://${prox[1]}:${prox[2]}`

    ],
    headless: false,


});


async function main() {
    puppeteerExtra.use(pluginStealth());
    let prox = proxies[proxyIndex++ % proxies.length].match(proxyRegex);
    if (!isTest && useProxy) puppeteerExtra.use(pluginProxy({
        address: prox[1],
        port: prox[2],
        credentials: {
            username: prox[3],
            password: prox[4],
        }
    }));
    const browser = await puppeteerExtra.launch(chromeOptions(prox));
    try {

        const page = await browser.newPage();
        await page.setRequestInterception(true);
        page.on('request', (request) => {
            if (['image', 'font'].indexOf(request.resourceType()) !== -1) {
                request.abort();
            } else {
                request.continue();
            }
        });
        await page.goto('https://www.dextools.io/app/pancakeswap/pair-explorer/0x378b30b02cec17983227935cf71ea85249da4067');
        await page.waitForSelector('li.text-right');
        page.waitForTimeout(1000)

        await clickStar(page);
        // const password = getPassword();
        page.waitForTimeout(500)


        await clickTrade(page);
        page.waitForTimeout(500)


    } catch (error) {
        console.log(error);
    }
}
const clickStar = async (page) => {
    await page.evaluate(() => {
        alert("aaa")
        let el = document.querySelectorAll("li.text-right")[0].children[2];
        console.log(el)
        el.click()
    });
}
const clickTrade = async (page) => {
    await page.evaluate(() => {
        let el = document.querySelectorAll("li.text-right")[0].children[3];
        console.log(el)

        // el.click()
    });
}


(async () => {
    // while (true) {
    //     try {
    //         await main();

    //     } catch (err) {
    //         console.log(err)
    //     } finally {
    //         setTimeout(main, 30000000000000000000000);

    //     }

    // }
    await main();

})()